In [1]:
# Numpy 자료형 코드 변경하기

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [2]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [3]:
float_arr

array([1., 2., 3., 4., 5.])

In [6]:
received = input("데이터 5개 입력").split()
str_num_arr = np.array(received, dtype=np.string_)
str_num_arr.dtype

데이터 5개 입력1 2 3 4 5


dtype('S1')

In [10]:
numer_num_arr = str_num_arr.astype(float)
numer_num_arr.dtype

dtype('float64')

In [11]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [13]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [16]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [17]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[4] = 40
arr

array([ 0,  1,  2,  3, 40,  5,  6,  7,  8,  9])

In [22]:
arr[5:8] = 13
arr

array([ 0,  1,  2,  3, 40, 13, 13, 13,  8,  9])

In [23]:
arr_slice = arr[5:8]
arr_slice

array([13, 13, 13])

In [33]:
arr_slice[1] = 100
arr

array([  0,   1,   2,   3,  40, 100, 100, 100,   8,   9])

In [32]:
arr_slice

array([100, 100, 100])

In [30]:
arr_slice[:] = 100 # arr_slice에 대한 내용 일괄 변경
arr_slice

array([100, 100, 100])

In [31]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy

array([100, 100, 100])

In [36]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
arr.T # 배열 전치(transpose)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
arr = np.random.randn(6,3)
arr

array([[ 1.28417526, -0.61069132,  1.84964562],
       [-0.63829268,  0.81422741,  0.7775627 ],
       [-0.51962935,  1.53143308,  1.72306586],
       [-0.67790681,  0.71637163,  0.31467493],
       [-1.17249628, -0.07205659, -1.43828348],
       [-0.78874073, -0.16049847,  0.57286386]])

In [39]:
np.dot(arr.T, arr) # 3 * 6  6 * 3 = 3 * 3

array([[ 4.78295541, -2.37428308,  2.00482167],
       [-2.37428308,  3.92533766,  2.37942861],
       [ 2.00482167,  2.37942861,  9.49060131]])

In [42]:
# 단항 유니버셜 함수
arr = np.arange(10)
np.sqrt(arr) # sqrt(..) .. 데이터 값에 루트 씌우기
np.exp(arr) # exp(..) .. 데이터 값에 지수승

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [43]:
# 이항 유니버셜 함수
x = np.random.randn(4)
y = np.random.randn(4)
z = np.maximum(x, y)
print(x);print(y);print(z)

[-0.44886347  0.01652541  0.72518802 -0.58684506]
[0.25563825 0.21061935 0.66673312 0.80338458]
[0.25563825 0.21061935 0.72518802 0.80338458]


In [46]:
arr = np.random.randn(5, 4) # (행, 열)
print(arr);print(arr.sum());print(arr.mean())# np.mean(arr)

[[-1.43459547  1.6016996  -1.78925094  1.15211704]
 [-0.00887707  0.7415655  -2.14294019  3.13276465]
 [ 0.98180798 -0.08225875 -1.58131221  0.67131794]
 [ 0.29704851 -1.65014531  0.40801166  0.04128327]
 [-0.38304425  0.17713104 -0.97842704  0.22750084]]
-0.6186031995596157
-0.030930159977980785


In [47]:
arr = np.random.randn(5, 4) # (행, 열)
print(arr.mean(axis=0));print(arr.mean(axis=1))

[0.21518914 0.46243928 0.23177525 0.58755789]
[ 0.09897588 -0.894372    1.25022895  1.35556884  0.06080027]
