In [1]:
# Numpy 자료형 코드 변경하기

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [2]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [3]:
float_arr

array([1., 2., 3., 4., 5.])

In [6]:
received = input("데이터 5개 입력").split()
str_num_arr = np.array(received, dtype=np.string_)
str_num_arr.dtype

데이터 5개 입력1 2 3 4 5


dtype('S1')

In [10]:
numer_num_arr = str_num_arr.astype(float)
numer_num_arr.dtype

dtype('float64')

In [11]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [13]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [16]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [17]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[4] = 40
arr

array([ 0,  1,  2,  3, 40,  5,  6,  7,  8,  9])

In [22]:
arr[5:8] = 13
arr

array([ 0,  1,  2,  3, 40, 13, 13, 13,  8,  9])

In [23]:
arr_slice = arr[5:8]
arr_slice

array([13, 13, 13])

In [33]:
arr_slice[1] = 100
arr

array([  0,   1,   2,   3,  40, 100, 100, 100,   8,   9])

In [32]:
arr_slice

array([100, 100, 100])

In [30]:
arr_slice[:] = 100 # arr_slice에 대한 내용 일괄 변경
arr_slice

array([100, 100, 100])

In [31]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy

array([100, 100, 100])