In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for i in range(10): my_arr2=my_arr*2


Wall time: 16 ms


In [3]:
%time for i in range(10): my_arr2=[x *2 for x in my_list]

Wall time: 727 ms


In [7]:
data = np.random.randn(2,3)
data

array([[-1.35990807, -0.39923576,  0.27865323],
       [ 0.7121545 , -2.90902102, -0.76302522]])

In [8]:
data * 10

array([[-13.59908066,  -3.99235759,   2.78653225],
       [  7.12154499, -29.09021019,  -7.63025217]])

In [9]:
data + data

array([[-2.71981613, -0.79847152,  0.55730645],
       [ 1.424309  , -5.81804204, -1.52605043]])

In [11]:
data.shape # data의 행렬 확인

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [14]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2d = [[1,2,3,4], [5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2d = np.array(data2d)

In [17]:
arr2d.ndim #차원 확인

2

In [18]:
arr2d.shape #행열확인

(2, 4)

In [21]:
np.zeros(10)
np.zeros((3,6)) # zeros는 하나의 입력값만 수행 -> 괄호로 묶어서 튜플처리
np.zeros((2,3,2)) # 3차원 행열로 표시, 거의 사용 X

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.zeros((2,3,2)).dtype

dtype('float64')

In [23]:
arr1 = np.zeros((2,3))
arr2 = np.ones_like(arr1)
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr3 = np.full((2,3),5) # 5로 2행3열 다채우고싶다
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [26]:
arr4 = np.eye(3)  # np.eye(n) n행 n열로 출력
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])